version: '3'
services:

  nodejs:
    image: nodejs
    build:
      context: ..
      dockerfile: Docker/nodejs.Dockerfile
    volumes:
      - ..:/data
    user: '1000'
    working_dir: /data
    hostname: nodejs